# Generated by Django 4.2.29 on 2026-07-28 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('device_id', models.CharField(help_text='Hardware/OS unique identifier', max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, help_text="Human-friendly name, e.g. 'Field Tablet – Manzini'", max_length=100)),
                ('app_version', models.CharField(blank=True, help_text='CoopData app version installed on this device', max_length=20)),
                ('platform', models.CharField(blank=True, help_text='e.g. Android, iOS, PWA', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='PendingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('payload', models.JSONField(help_text='JSON snapshot of all changed fields and their new values')),
                ('local_timestamp', models.DateTimeField(help_text='When the change was made on the device (device clock)')),
                ('server_received_at', models.DateTimeField(auto_now_add=True, help_text='When the server received this change')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('conflict', 'Conflict – Needs Review')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pending Change',
                'verbose_name_plural': 'Pending Changes',
                'ordering': ['local_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_start_time', models.DateTimeField(auto_now_add=True)),
                ('sync_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial – Some Changes Failed'), ('failed', 'Failed')], default='success', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('changes_uploaded', models.PositiveIntegerField(default=0)),
                ('changes_downloaded', models.PositiveIntegerField(default=0)),
                ('conflicts_detected', models.PositiveIntegerField(default=0)),
                ('bytes_uploaded', models.PositiveIntegerField(default=0)),
                ('bytes_downloaded', models.PositiveIntegerField(default=0)),
                ('connection_type', models.CharField(blank=True, help_text='e.g. wifi, 3G, 4G, satellite', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='sync.device')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-sync_start_time'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('server_snapshot', models.JSONField(help_text='State of the record on the server at the time of conflict')),
                ('device_snapshot', models.JSONField(help_text='State proposed by the device')),
                ('conflicting_fields', models.JSONField(default=list, help_text='List of field names that differ between device and server')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('client_wins', 'Accept Device Version'), ('server_wins', 'Keep Server Version'), ('manual_merge', 'Manual Merge')], max_length=20)),
                ('final_state', models.JSONField(blank=True, help_text='The merged/chosen final state applied to the database', null=True)),
                ('notes', models.TextField(blank=True)),
                ('pending_change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conflict', to='sync.pendingchange')),
            ],
            options={
                'verbose_name': 'Sync Conflict',
                'verbose_name_plural': 'Sync Conflicts',
                'ordering': ['-detected_at'],
            },
        ),
    ]
