# Generated by Django 4.2.28 on 2026-03-10 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique identifier for the mobile device', max_length=255, unique=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_start_time', models.DateTimeField(auto_now_add=True)),
                ('sync_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(help_text='e.g., Success, Failed, Partial', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('changes_uploaded', models.PositiveIntegerField(default=0)),
                ('changes_downloaded', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='sync.device')),
            ],
            options={
                'verbose_name': 'Synchronization Log',
                'verbose_name_plural': 'Synchronization Logs',
                'ordering': ['-sync_start_time'],
            },
        ),
        migrations.CreateModel(
            name='PendingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('payload', models.JSONField(help_text='JSON representation of the changed data')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='sync.device')),
            ],
            options={
                'verbose_name': 'Pending Change',
                'verbose_name_plural': 'Pending Changes',
                'ordering': ['timestamp'],
            },
        ),
    ]
