# Generated by Django 5.2.5 on 2026-03-12 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingchange',
            name='local_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='conflict_strategy',
            field=models.CharField(blank=True, choices=[('last_write_wins', 'Last write wins'), ('server_wins', 'Server wins'), ('client_wins', 'Client wins'), ('manual', 'Manual resolution')], max_length=32, null=True),
        ),
    ]
