# Generated by Django 4.2.29 on 2026-03-13 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_pendingchange_local_uuid_synclog_conflict_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='pendingchange',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
