# Generated by Django 4.2.29 on 2026-03-21 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync', '0003_device_unique_id_pendingchange_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('server_snapshot', models.JSONField(help_text='State of the record on the server at the time of conflict')),
                ('device_snapshot', models.JSONField(help_text='State proposed by the device')),
                ('conflicting_fields', models.JSONField(default=list, help_text='List of field names that differ between device and server')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('client_wins', 'Accept Device Version'), ('server_wins', 'Keep Server Version'), ('manual_merge', 'Manual Merge')], max_length=20)),
                ('final_state', models.JSONField(blank=True, help_text='The merged/chosen final state applied to the database', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sync Conflict',
                'verbose_name_plural': 'Sync Conflicts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='pendingchange',
            options={'ordering': ['local_timestamp'], 'verbose_name': 'Pending Change', 'verbose_name_plural': 'Pending Changes'},
        ),
        migrations.AlterModelOptions(
            name='synclog',
            options={'ordering': ['-sync_start_time'], 'verbose_name': 'Sync Log', 'verbose_name_plural': 'Sync Logs'},
        ),
        migrations.RemoveField(
            model_name='pendingchange',
            name='is_synced',
        ),
        migrations.RemoveField(
            model_name='pendingchange',
            name='local_uuid',
        ),
        migrations.RemoveField(
            model_name='pendingchange',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='conflict_strategy',
        ),
        migrations.AddField(
            model_name='device',
            name='app_version',
            field=models.CharField(blank=True, help_text='CoopData app version installed on this device', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, help_text="Human-friendly name, e.g. 'Field Tablet – Manzini'", max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.CharField(blank=True, help_text='e.g. Android, iOS, PWA', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingchange',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pendingchange',
            name='local_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the change was made on the device (device clock)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingchange',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pendingchange',
            name='server_received_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the server received this change'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingchange',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('conflict', 'Conflict – Needs Review')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='synclog',
            name='bytes_downloaded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='bytes_uploaded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='conflicts_detected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='connection_type',
            field=models.CharField(blank=True, help_text='e.g. wifi, 3G, 4G, satellite', max_length=20),
        ),
        migrations.AddField(
            model_name='synclog',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(help_text='Hardware/OS unique identifier', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingchange',
            name='payload',
            field=models.JSONField(help_text='JSON snapshot of all changed fields and their new values'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial – Some Changes Failed'), ('failed', 'Failed')], default='success', max_length=10),
        ),
        migrations.AddIndex(
            model_name='pendingchange',
            index=models.Index(fields=['state', 'device'], name='sync_pendin_state_a99744_idx'),
        ),
        migrations.AddField(
            model_name='syncconflict',
            name='pending_change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conflict', to='sync.pendingchange'),
        ),
        migrations.AddField(
            model_name='syncconflict',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL),
        ),
    ]
