# Generated by Django 4.2.29 on 2026-03-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='target_model',
            field=models.CharField(choices=[('cooperative', 'Cooperative'), ('member', 'Member'), ('user', 'User'), ('financial_record', 'Financial Record'), ('production', 'Production Record')], default='cooperative', max_length=50),
        ),
    ]
