# Generated by Django 4.2.29 on 2026-03-13 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_alter_questionnaire_target_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
