# Generated by Django 4.2.29 on 2026-03-13  

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0003_questionnaire_unique_id_submission_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="cooperatives",
            field=models.ManyToManyField(
                blank=True,
                related_name="questionnaires",
                to="cooperatives.cooperative",
                help_text="If filled, this questionnaire will apply only to the selected cooperatives.",
            ),
        ),
    ]
