# Generated by Django 4.2.29 on 2026-07-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('fr', 'Français'), ('sw', 'Kiswahili'), ('en', 'English')], default='fr', max_length=5),
        ),
    ]
