# Generated by Django 4.2.29 on 2026-03-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Cooperative Member'), ('agronomist', 'Agronomist'), ('supervisor', 'Agronomist Supervisor'), ('station_chef', 'Washing Station Chef'), ('manager', 'Cooperative Manager'), ('regional_officer', 'Regional Officer'), ('apex_body', 'Apex Body Representative'), ('government', 'Government Official'), ('admin', 'System Administrator')], default='member', max_length=20),
        ),
    ]
