# Generated by Django 4.2.29 on 2026-03-13 08:11

from django.db import migrations, models
import uuid


def generate_unique_ids(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(unique_id__isnull=True):
        user.unique_id = uuid.uuid4()
        user.save(update_fields=['unique_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.UUIDField(db_index=True, null=True, blank=True, editable=False),
        ),
        migrations.RunPython(generate_unique_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
