# Generated by Django 4.2.29 on 2026-03-19 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0008_washingstation_code_washingstation_created_at_and_more'),
        ('users', '0003_user_unique_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Région', 'verbose_name_plural': 'Régions'},
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.CharField(default='DRC', max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='cooperatives.cooperative'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('sw', 'Kiswahili'), ('en', 'English')], default='fr', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Cooperative Member'), ('field_agent', 'Field Agent'), ('manager', 'Cooperative Manager'), ('regional_officer', 'Regional Officer'), ('apex_body', 'Apex Body Representative'), ('government', 'Government Official'), ('admin', 'System Administrator'), ('agronomist', 'Agronomist'), ('supervisor', 'Agronomist Supervisor'), ('station_chef', 'Washing Station Chef')], default='member', max_length=20),
        ),
    ]
