# Generated by Django 4.2.29 on 2026-03-21 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_region_options_region_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['country_code', 'name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_sync_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='region',
            name='country_code',
            field=models.CharField(default='SZ', help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
        migrations.AddField(
            model_name='region',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Force user to change password on next login'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enrolled',
            field=models.BooleanField(default=False, help_text='True once the user has completed 2FA setup'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_marginalized',
            field=models.BooleanField(default=False, help_text='Flag for inclusion-based programmes (TOR §3.1)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_youth',
            field=models.BooleanField(default=False, help_text='Flag if user/member is aged 18-35'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ss', 'SiSwati'), ('pt', 'Portuguese')], default='en', help_text='Interface language preference', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('government', 'Government Official (MCIT)'), ('apex_body', 'Apex Body / Federation Representative'), ('regional_officer', 'Regional Officer'), ('sacco_manager', 'SACCO / Cooperative Manager'), ('field_agent', 'Field Agent / Data Collector'), ('member', 'Cooperative Member'), ('auditor', 'Auditor (Read-Only)')], db_index=True, default='member', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name', 'country_code')},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Record Created'), ('update', 'Record Updated'), ('delete', 'Record Deleted'), ('export', 'Report / Data Exported'), ('sync', 'Offline Sync'), ('role_change', 'User Role Changed')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('content_type_label', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
    ]
