# Generated by Django 4.2.29 on 2026-07-28 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type', models.CharField(choices=[('coffee', 'Coffee Cooperative'), ('cocoa', 'Cocoa Cooperative'), ('mixed', 'Mixed Coffee & Cocoa Cooperative'), ('other', 'Other Cooperative Type')], max_length=50)),
                ('establishment_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cooperative',
                'verbose_name_plural': 'Cooperatives',
            },
        ),
        migrations.CreateModel(
            name='CooperativeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expires_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(upload_to='cooperative_certificates/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cooperative Certificate',
                'verbose_name_plural': 'Cooperative Certificates',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='CooperativeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=50)),
                ('destination_country', models.CharField(max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cooperative Sale',
                'verbose_name_plural': 'Cooperative Sales',
                'ordering': ['-year', '-quantity_kg'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('farm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('size_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trees_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Trees')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('loan', 'Loan'), ('dividend', 'Dividend'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age_group', models.CharField(choices=[('youth', 'Youth (18-35)'), ('adult', 'Adult (36-60)'), ('senior', 'Senior (61+)')], max_length=10)),
                ('territory', models.CharField(blank=True, max_length=100, null=True, verbose_name='Territory')),
                ('groupement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Groupement')),
                ('village', models.CharField(blank=True, max_length=100, null=True, verbose_name='Village')),
                ('subvillage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-village / Localité')),
                ('farmer_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Farmer Code')),
                ('farmer_code_prefix', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('farmer_code_initials', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('farmer_code_number', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('is_marginalized', models.BooleanField(default=False, verbose_name='From Marginalized Group')),
                ('is_board_member', models.BooleanField(default=False, verbose_name='Board Member')),
                ('board_role', models.CharField(blank=True, choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('advisor', 'Advisor'), ('other', 'Other')], max_length=50, null=True, verbose_name='Board Role')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Member')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='WashingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('groupement', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washing_stations', to='cooperatives.cooperative')),
            ],
            options={
                'verbose_name': 'Washing Station',
                'verbose_name_plural': 'Washing Stations',
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('record_type', models.CharField(choices=[('generic', 'Generic'), ('cherry_delivery', 'Cherry Delivery')], db_index=True, default='generic', max_length=20)),
                ('crop_type', models.CharField(choices=[('coffee', 'Coffee'), ('cocoa', 'Cocoa')], max_length=50)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('reception_date', models.DateField(blank=True, null=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('base_price_fc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price_fc', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('exchange_rate_fc_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cherry_register_number', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_report_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True)),
                ('is_locally_created', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='cooperatives.farm')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to='cooperatives.member')),
            ],
            options={
                'verbose_name': 'Production Record',
                'verbose_name_plural': 'Production Records',
                'ordering': ['-harvest_date'],
            },
        ),
    ]
