# Generated by Django 4.2.29 on 2026-07-28 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='production_records_participated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to='cooperatives.washingstation'),
        ),
        migrations.AddField(
            model_name='member',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cooperatives.cooperative'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='cooperatives.cooperative'),
        ),
        migrations.AddField(
            model_name='farm',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='cooperatives.member'),
        ),
        migrations.AddField(
            model_name='cooperativesale',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cooperatives.buyer'),
        ),
        migrations.AddField(
            model_name='cooperativesale',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='cooperatives.cooperative'),
        ),
        migrations.AddField(
            model_name='cooperativecertificate',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='cooperatives.cooperative'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cooperatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cooperatives', to='users.region'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('cooperative', 'member_id')},
        ),
    ]
