# Generated by Django 4.2.28 on 2026-03-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='board_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Board Role'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_board_member',
            field=models.BooleanField(default=False, verbose_name='Board Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_marginalized',
            field=models.BooleanField(default=False, verbose_name='From Marginalized Group'),
        ),
    ]
