# Generated by Django 5.2.5 on 2026-03-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0002_member_board_role_member_is_board_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='trees_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Trees'),
        ),
        migrations.AddField(
            model_name='member',
            name='groupement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Groupement'),
        ),
        migrations.AddField(
            model_name='member',
            name='territory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Territory'),
        ),
        migrations.AddField(
            model_name='member',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Village'),
        ),
        migrations.AlterField(
            model_name='member',
            name='board_role',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('advisor', 'Advisor'), ('other', 'Other')], max_length=50, null=True, verbose_name='Board Role'),
        ),
    ]
