# Generated by Django 5.2.5 on 2026-03-12 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_farm_trees_count_member_groupement_member_territory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='farmer_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Farmer Code'),
        ),
        migrations.AddField(
            model_name='member',
            name='farmer_code_initials',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='farmer_code_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='farmer_code_prefix',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='subvillage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-village / Localité'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='base_price_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='cherry_register_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='delivery_report_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='exchange_rate_fc_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='is_locally_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to='cooperatives.member'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='reception_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='record_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('cherry_delivery', 'Cherry Delivery')], db_index=True, default='generic', max_length=20),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='sync_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='total_price_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='cooperatives.farm'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WashingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washing_stations', to='cooperatives.cooperative')),
            ],
            options={
                'verbose_name': 'Washing Station',
                'verbose_name_plural': 'Washing Stations',
            },
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to='cooperatives.washingstation'),
        ),
    ]
