# Generated by Django 4.2.29 on 2026-03-12 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperatives', '0004_member_farmer_code_member_farmer_code_initials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='production_records_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
