# Generated by Django 4.2.29 on 2026-03-13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cooperatives", "0006_cooperative_unique_id_farm_unique_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Buyer",
                "verbose_name_plural": "Buyers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CooperativeCertificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("issuer", models.CharField(blank=True, max_length=255, null=True)),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("expires_date", models.DateField(blank=True, null=True)),
                ("document", models.FileField(upload_to="cooperative_certificates/")),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "cooperative",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="certificates",
                        to="cooperatives.cooperative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cooperative Certificate",
                "verbose_name_plural": "Cooperative Certificates",
                "ordering": ["-issued_date"],
            },
        ),
        migrations.CreateModel(
            name="CooperativeSale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("year", models.PositiveIntegerField()),
                ("grade", models.CharField(max_length=50)),
                ("destination_country", models.CharField(max_length=100)),
                ("quantity_kg", models.DecimalField(max_digits=12, decimal_places=2)),
                ("price_per_kg", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("total_value", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("arrival_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=models.PROTECT,
                        related_name="sales",
                        to="cooperatives.buyer",
                    ),
                ),
                (
                    "cooperative",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="sales",
                        to="cooperatives.cooperative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cooperative Sale",
                "verbose_name_plural": "Cooperative Sales",
                "ordering": ["-year", "-quantity_kg"],
            },
        ),
    ]
