# Generated by Django 4.2.29 on 2026-03-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0007_add_buyer_certificate_sale_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='washingstation',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='washingstation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='washingstation',
            name='groupement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='washingstation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
