# Generated by Django 4.2.29 on 2026-03-21 10:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperatives', '0008_washingstation_code_washingstation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('position', models.CharField(choices=[('chairperson', 'Chairperson'), ('vice_chairperson', 'Vice-Chairperson'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Board Member'), ('supervisor', 'Supervisory Committee Member')], max_length=30)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Prefer not to say')], max_length=10)),
                ('is_youth', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Board Member',
                'verbose_name_plural': 'Board Members',
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('loan_id', models.CharField(max_length=50, unique=True)),
                ('disbursement_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Annual interest rate', max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arrears_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount in arrears (overdue)', max_digits=12)),
                ('days_in_arrears', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed / Repaid'), ('written_off', 'Written Off'), ('restructured', 'Restructured')], default='active', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('mambu_encoded_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Loan Account',
                'verbose_name_plural': 'Loan Accounts',
                'ordering': ['-disbursement_date'],
            },
        ),
        migrations.CreateModel(
            name='SACCOFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_equity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('share_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('retained_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_loan_portfolio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loans_disbursed_period', models.DecimalField(decimal_places=2, default=0, help_text='Total loans disbursed during this period', max_digits=15)),
                ('loan_repayments_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('par_30_days', models.DecimalField(decimal_places=2, default=0, help_text='Outstanding balance of loans overdue > 30 days', max_digits=15)),
                ('par_90_days', models.DecimalField(decimal_places=2, default=0, help_text='Outstanding balance of loans overdue > 90 days', max_digits=15)),
                ('write_offs_period', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loan_loss_provisions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fee_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_surplus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('active_borrowers', models.PositiveIntegerField(default=0)),
                ('active_savers', models.PositiveIntegerField(default=0)),
                ('new_members_period', models.PositiveIntegerField(default=0)),
                ('female_members', models.PositiveIntegerField(default=0)),
                ('youth_members', models.PositiveIntegerField(default=0)),
                ('kpi_delinquency_rate', models.DecimalField(blank=True, decimal_places=4, help_text='PAR30 / Gross Loan Portfolio', max_digits=6, null=True)),
                ('kpi_liquidity_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Liquid Assets / Total Deposits', max_digits=6, null=True)),
                ('kpi_capital_adequacy', models.DecimalField(blank=True, decimal_places=4, help_text='Total Equity / Total Assets', max_digits=6, null=True)),
                ('kpi_roa', models.DecimalField(blank=True, decimal_places=4, help_text='Net Surplus / Average Total Assets', max_digits=6, null=True)),
                ('kpi_cost_per_borrower', models.DecimalField(blank=True, decimal_places=2, help_text='Operating Expenses / Active Borrowers', max_digits=10, null=True)),
                ('kpi_portfolio_yield', models.DecimalField(blank=True, decimal_places=4, help_text='Interest Income / Average Gross Loan Portfolio', max_digits=6, null=True)),
                ('kpi_operational_self_sufficiency', models.DecimalField(blank=True, decimal_places=4, help_text='Total Income / (Operating + Loan Loss + Interest Expenses)', max_digits=6, null=True)),
                ('kpi_youth_participation_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Youth Members / Total Members', max_digits=6, null=True)),
                ('kpi_female_participation_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('kpi_training_hours_per_member', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'SACCO Financial Summary',
                'verbose_name_plural': 'SACCO Financial Summaries',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('shares', 'Share Capital Account'), ('savings', 'Voluntary Savings Account'), ('fixed_deposit', 'Fixed / Term Deposit'), ('holiday', 'Holiday / Club Savings')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Annual interest rate, e.g. 0.0350 = 3.50%', max_digits=5)),
                ('opened_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('mambu_encoded_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Savings Account',
                'verbose_name_plural': 'Savings Accounts',
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('training_date', models.DateField()),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('female_participants', models.PositiveIntegerField(default=0)),
                ('youth_participants', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Training Record',
                'verbose_name_plural': 'Training Records',
                'ordering': ['-training_date'],
            },
        ),
        migrations.RemoveField(
            model_name='cooperativecertificate',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='cooperativesale',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='cooperativesale',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='member',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='member',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='station',
        ),
        migrations.RemoveField(
            model_name='washingstation',
            name='cooperative',
        ),
        migrations.AlterModelOptions(
            name='cooperative',
            options={'ordering': ['name'], 'verbose_name': 'Cooperative', 'verbose_name_plural': 'Cooperatives'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.RenameField(
            model_name='cooperative',
            old_name='address',
            new_name='physical_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='board_role',
        ),
        migrations.RemoveField(
            model_name='member',
            name='farmer_code',
        ),
        migrations.RemoveField(
            model_name='member',
            name='farmer_code_initials',
        ),
        migrations.RemoveField(
            model_name='member',
            name='farmer_code_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='farmer_code_prefix',
        ),
        migrations.RemoveField(
            model_name='member',
            name='groupement',
        ),
        migrations.RemoveField(
            model_name='member',
            name='subvillage',
        ),
        migrations.RemoveField(
            model_name='member',
            name='territory',
        ),
        migrations.RemoveField(
            model_name='member',
            name='village',
        ),
        migrations.AddField(
            model_name='cooperative',
            name='apex_body',
            field=models.ForeignKey(blank=True, help_text='Parent Apex body or Federation, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_cooperatives', to='cooperatives.cooperative'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperative',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='mambu_encoded_key',
            field=models.CharField(blank=True, help_text='Mambu branch/centre encoded key for API sync', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='mambu_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='postal_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='sector',
            field=models.CharField(blank=True, help_text='Economic sector, e.g. agriculture, finance, retail', max_length=100),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('deregistered', 'Deregistered'), ('pending', 'Pending Registration')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='exit_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_youth',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='type',
            field=models.CharField(choices=[('sacco', 'SACCO (Savings & Credit Cooperative)'), ('agricultural', 'Agricultural Cooperative'), ('consumer', 'Consumer Cooperative'), ('housing', 'Housing Cooperative'), ('multipurpose', 'Multi-Purpose Cooperative'), ('worker', 'Worker / Producer Cooperative'), ('other', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='age_group',
            field=models.CharField(choices=[('youth', 'Youth (18–35)'), ('adult', 'Adult (36–60)'), ('senior', 'Senior (61+)'), ('under18', 'Under 18')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Prefer not to say')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_board_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_marginalized',
            field=models.BooleanField(db_index=True, default=False, help_text='Persons with disabilities, widows, displaced persons, etc.'),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='CooperativeCertificate',
        ),
        migrations.DeleteModel(
            name='CooperativeSale',
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
        migrations.DeleteModel(
            name='FinancialRecord',
        ),
        migrations.DeleteModel(
            name='ProductionRecord',
        ),
        migrations.DeleteModel(
            name='WashingStation',
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='cooperatives.cooperative'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_accounts', to='cooperatives.member'),
        ),
        migrations.AddField(
            model_name='saccofinancialsummary',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summaries', to='cooperatives.cooperative'),
        ),
        migrations.AddField(
            model_name='saccofinancialsummary',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saccofinancialsummary',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_accounts', to='cooperatives.member'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='cooperatives.cooperative'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_positions', to='cooperatives.member'),
        ),
        migrations.AlterUniqueTogether(
            name='savingsaccount',
            unique_together={('member', 'account_number')},
        ),
        migrations.AlterUniqueTogether(
            name='saccofinancialsummary',
            unique_together={('cooperative', 'period_type', 'period_start')},
        ),
    ]
