# Generated by Django 4.2.29 on 2026-07-28 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(help_text="e.g. 'ITC Benchmark', 'National Cooperative Standard'", max_length=50)),
                ('green_min', models.DecimalField(blank=True, decimal_places=4, help_text='Value at or above which performance is GREEN', max_digits=10, null=True)),
                ('green_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('amber_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('amber_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('red_threshold', models.DecimalField(blank=True, decimal_places=4, help_text='Value at or below (for higher-is-better) which performance is RED', max_digits=10, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Apply this threshold to all cooperatives by default')),
            ],
            options={
                'verbose_name': 'Benchmark Threshold',
                'verbose_name_plural': 'Benchmark Thresholds',
            },
        ),
        migrations.CreateModel(
            name='DataQualityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cooperative_id', models.PositiveIntegerField(help_text='ID of the Cooperative that owns the offending record')),
                ('content_type_label', models.CharField(max_length=100)),
                ('record_id', models.PositiveIntegerField(help_text='PK of the record that triggered the alert')),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('offending_value', models.TextField(blank=True)),
                ('message', models.TextField()),
                ('alert_date', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Data Quality Alert',
                'verbose_name_plural': 'Data Quality Alerts',
                'ordering': ['-alert_date'],
            },
        ),
        migrations.CreateModel(
            name='DataValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rule_expression', models.TextField(help_text="Safe Python expression, e.g. 'value > 0' or 'par_30_days / gross_loan_portfolio > 0.25'")),
                ('applies_to_model', models.CharField(help_text="e.g. 'cooperatives.ProductionRecord'", max_length=100)),
                ('applies_to_field', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(choices=[('error', 'Error – blocks submission'), ('warning', 'Warning – flags for review')], default='warning', max_length=10)),
                ('error_message_template', models.TextField(blank=True, help_text='Human-readable message shown to users when rule is violated. Use {field} and {value} placeholders.')),
                ('auto_fix_hint', models.TextField(blank=True, help_text='Suggested corrective action for the data entry officer')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Validation Rule',
                'verbose_name_plural': 'Data Validation Rules',
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel (.xlsx)'), ('docx', 'Word (.docx)')], max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('file_url', models.URLField(blank=True, help_text='Cloudinary or S3 URL of generated file')),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parameters_snapshot', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('operational', 'Operational'), ('social', 'Social / Inclusion'), ('governance', 'Governance')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, help_text='e.g. % (percentage), FC, USD, kg, ratio', max_length=30)),
                ('source_field', models.CharField(blank=True, help_text='Model field name where pre-computed value is stored', max_length=100)),
                ('formula_description', models.TextField(blank=True, help_text='Plain-language description of how this KPI is calculated')),
                ('higher_is_better', models.BooleanField(default=True, help_text='False for KPIs where a lower value is healthier (e.g. delinquency)')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(blank=True, help_text='JSON: {kpis:[...], filters:{region, sector, gender, age_group}, period_type, comparison_periods}', null=True)),
                ('scope', models.CharField(choices=[('system', 'System-wide'), ('cooperative', 'Single Cooperative'), ('region', 'Region')], default='system', max_length=15)),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel (.xlsx)'), ('docx', 'Word (.docx)')], default='pdf', max_length=5)),
                ('allowed_roles', models.JSONField(default=list, help_text="List of role slugs, e.g. ['government','apex_body']")),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_cron', models.CharField(blank=True, help_text="Cron expression, e.g. '0 6 1 * *' = 1st of every month at 06:00", max_length=50)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Configuration',
                'verbose_name_plural': 'Report Configurations',
                'ordering': ['name'],
            },
        ),
    ]
