# Generated by Django 4.2.28 on 2026-03-10 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.PositiveIntegerField(help_text='ID of the record that triggered the alert')),
                ('message', models.TextField()),
                ('alert_date', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Quality Alert',
                'verbose_name_plural': 'Data Quality Alerts',
                'ordering': ['-alert_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('viewable_by_roles', models.ManyToManyField(blank=True, related_name='viewable_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Configuration',
                'verbose_name_plural': 'Report Configurations',
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('calculation_formula', models.TextField(help_text='Python code snippet or description of how the KPI is calculated')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key Performance Indicator',
                'verbose_name_plural': 'Key Performance Indicators',
            },
        ),
        migrations.CreateModel(
            name='DataValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_expression', models.TextField(help_text='Python code snippet or expression for validation')),
                ('applies_to_model', models.CharField(help_text="e.g., 'cooperatives.ProductionRecord'", max_length=100)),
                ('applies_to_field', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Validation Rule',
                'verbose_name_plural': 'Data Validation Rules',
            },
        ),
    ]
