# Generated by Django 4.2.29 on 2026-03-19 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0008_washingstation_code_washingstation_created_at_and_more'),
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_results', to='cooperatives.cooperative')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.kpi')),
            ],
            options={
                'verbose_name': 'KPI Result',
                'verbose_name_plural': 'KPI Results',
                'ordering': ['-period_end'],
                'unique_together': {('kpi', 'cooperative', 'period_start', 'period_end')},
            },
        ),
    ]
