# Generated by Django 4.2.29 on 2026-03-21 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0003_kpiresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(help_text="e.g. 'Eswatini SACCO Standard', 'WOCCU Best Practice'", max_length=50)),
                ('green_min', models.DecimalField(blank=True, decimal_places=4, help_text='Value at or above which performance is GREEN', max_digits=10, null=True)),
                ('green_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('amber_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('amber_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('red_threshold', models.DecimalField(blank=True, decimal_places=4, help_text='Value at or below (for higher-is-better) which performance is RED', max_digits=10, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Apply this threshold to all cooperatives by default')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benchmark Threshold',
                'verbose_name_plural': 'Benchmark Thresholds',
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel (.xlsx)'), ('docx', 'Word (.docx)')], max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('file_url', models.URLField(blank=True, help_text='Cloudinary or S3 URL of generated file')),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parameters_snapshot', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'KPI', 'verbose_name_plural': 'KPIs'},
        ),
        migrations.AlterModelOptions(
            name='reportconfiguration',
            options={'ordering': ['name'], 'verbose_name': 'Report Configuration', 'verbose_name_plural': 'Report Configurations'},
        ),
        migrations.RemoveField(
            model_name='dataqualityalert',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='calculation_formula',
        ),
        migrations.RemoveField(
            model_name='reportconfiguration',
            name='viewable_by_roles',
        ),
        migrations.AddField(
            model_name='dataqualityalert',
            name='content_type_label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataqualityalert',
            name='cooperative_id',
            field=models.PositiveIntegerField(default=1, help_text='ID of the Cooperative that owns the offending record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataqualityalert',
            name='field_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dataqualityalert',
            name='offending_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataqualityalert',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataqualityalert',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='datavalidationrule',
            name='auto_fix_hint',
            field=models.TextField(blank=True, help_text='Suggested corrective action for the data entry officer'),
        ),
        migrations.AddField(
            model_name='datavalidationrule',
            name='error_message_template',
            field=models.TextField(blank=True, help_text='Human-readable message shown to users when rule is violated. Use {field} and {value} placeholders.'),
        ),
        migrations.AddField(
            model_name='datavalidationrule',
            name='severity',
            field=models.CharField(choices=[('error', 'Error – blocks submission'), ('warning', 'Warning – flags for review')], default='warning', max_length=10),
        ),
        migrations.AddField(
            model_name='datavalidationrule',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='category',
            field=models.CharField(choices=[('financial', 'Financial'), ('operational', 'Operational'), ('social', 'Social / Inclusion'), ('governance', 'Governance')], db_index=True, default='general', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpi',
            name='display_order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='kpi',
            name='formula_description',
            field=models.TextField(blank=True, help_text='Plain-language description of how this KPI is calculated'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='higher_is_better',
            field=models.BooleanField(default=True, help_text='False for KPIs where a lower value is healthier (e.g. delinquency)'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='slug',
            field=models.SlugField(default="", max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpi',
            name='source_field',
            field=models.CharField(blank=True, help_text='Model field name where pre-computed value is stored', max_length=100),
        ),
        migrations.AddField(
            model_name='kpi',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g. % (percentage), SZL, ratio, hours', max_length=30),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='allowed_roles',
            field=models.JSONField(default=list, help_text="List of role slugs, e.g. ['government','apex_body']"),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='default_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel (.xlsx)'), ('docx', 'Word (.docx)')], default='pdf', max_length=5),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='schedule_cron',
            field=models.CharField(blank=True, help_text="Cron expression, e.g. '0 6 1 * *' = 1st of every month at 06:00", max_length=50),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='scope',
            field=models.CharField(choices=[('system', 'System-wide'), ('cooperative', 'Single Cooperative'), ('region', 'Region')], default='system', max_length=15),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dataqualityalert',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='dataqualityalert',
            name='record_id',
            field=models.PositiveIntegerField(help_text='PK of the record that triggered the alert'),
        ),
        migrations.AlterField(
            model_name='datavalidationrule',
            name='applies_to_model',
            field=models.CharField(help_text="e.g. 'cooperatives.SACCOFinancialSummary'", max_length=100),
        ),
        migrations.AlterField(
            model_name='datavalidationrule',
            name='description',
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datavalidationrule',
            name='rule_expression',
            field=models.TextField(help_text="Safe Python expression, e.g. 'value > 0' or 'par_30_days / gross_loan_portfolio > 0.25'"),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='description',
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='description',
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='parameters',
            field=models.JSONField(blank=True, help_text='JSON: {kpis:[...], filters:{region, sector, gender, age_group}, period_type, comparison_periods}', null=True),
        ),
        migrations.DeleteModel(
            name='KPIResult',
        ),
        migrations.AddField(
            model_name='exportjob',
            name='report_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='analytics.reportconfiguration'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benchmarkthreshold',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='analytics.kpi'),
        ),
    ]
